# Copy this file into one without .sample part and then populate it with actual values.
# Then you can create secret, by using command
# `sem create -f path/to/this/file`
# More info https://docs.semaphoreci.com/article/66-environment-variables-and-secrets
apiVersion: v1beta
kind: Secret
metadata:
  # Use this name to create this secret manually
  name: netlify-authentication
data:
  files:
  # Download netlify cli `sudo npm install netlify-cli -g`
  # Authorize your terminal using `netlify login`.
  # This will create ~/.netlify/config.json which we'll use soon.
  #
  - path: ~/.netlify/config.json
    # Could be created by
    # - `base64 -w 0 /path/to/config.json`
    content: ewoJInRlbGVtZXRyeURpc2FibGVkIjogZmFsc2UsCgkiY2xpSWQiOiAiYmQyYzljOWEtMTQ2Mi00M2I3LTkzZTItOWFkZmRmNGJhZWZmIiwKCSJ1c2VySWQiOiAiNWQ3OGEwYjcwNGNiM2ZjODEyYjNiYzNiIiwKCSJ1c2VycyI6IHsKCQkiNWQ3OGEwYjcwNGNiM2ZjODEyYjNiYzNiIjogewoJCQkiaWQiOiAiNWQ3OGEwYjcwNGNiM2ZjODEyYjNiYzNiIiwKCQkJIm5hbWUiOiAiTWF0dGhldyBEYW5pZWwgTXVycGh5IiwKCQkJImVtYWlsIjogIm1hdHRAbWF0dG11cnBoeS5jYSIsCgkJCSJhdXRoIjogewoJCQkJInRva2VuIjogIjdiNmM3YWQ3NDQ4MjAzN2E5OWY4YTBjYzM1Mzc3MjExYWNhZTlkYTdkYTNlMGJmZjJiZjcxNTMwYzQ5ZWYxMjEiLAoJCQkJImdpdGh1YiI6IHt9CgkJCX0KCQl9Cgl9Cn0=

  # If you haven't already, create a "New site from Git" in Netlify.
  # Link your CLI to the project which you created, using `netlify link`.
  # This will create ~/.netlify/state.json which we'll use soon.
  # 
  - path: ../../.netlify/state.json
    # Could be created by
    # - `base64 -w 0 /path/to/state.json`
    content: ewoJInNpdGVJZCI6ICJmMDQzNGQzNy05OTczLTRjZjUtYjkxOS05ZjU0MWFmNGY5MWQiCn0=
